"""empty message

Revision ID: f89c6ba01095
Revises: 070a5d3f612a
Create Date: 2025-04-04 17:36:57.226425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89c6ba01095'
down_revision = '070a5d3f612a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reader_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('comentarios_writer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'reader', ['reader_id'], ['id'])
        batch_op.drop_column('writer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('writer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comentarios_writer_id_fkey', 'writer', ['writer_id'], ['id'])
        batch_op.drop_column('reader_id')

    # ### end Alembic commands ###
